substitutions:
  _REGION: "southamerica-east1"
  _SERVICE_ACCOUNT: "cloud-run-crm@YOUR_PROJECT_ID.iam.gserviceaccount.com"
  _CLOUD_SQL_CONNECTION: "YOUR_PROJECT_ID:southamerica-east1:elitte-crm-db"
  _SERVICE_NAME: "elitte-backend"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "backend/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "backend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--service-account",
        "${_SERVICE_ACCOUNT}",
        "--add-cloudsql-instances",
        "${_CLOUD_SQL_CONNECTION}",
        "--set-env-vars",
        "PORT=3000",
      ]

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"
